/*
 * config.java
 *
 * Created on July 25, 2005, 7:46 AM
 */

package org.jdesktop.lg3d.apps.weather;

/**
 *
 * @author  thehole
 */
public class config extends javax.swing.JFrame {
    
    /** Creates new form config */
    public config() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather Editor");
        getAccessibleContext().setAccessibleParent(this);
        jPanel1.setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 430));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 350, 560, 50);

        jButton1.setText("Cancel");
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 360, 80, 25);

        jButton2.setText("Next >");
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 360, 76, 25);

        jButton3.setText("< Back");
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 360, 77, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 700, 430);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new config().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
}
