@echo off
gml_nodes_lg.pl 95 newXML\bardeenJ.xml
gml_nodes_lg.pl 114 newXML\_beaumarchaisPACde.xml
gml_nodes_lg.pl 116 newXML\_beccariaC.xml
gml_nodes_lg.pl 126 newXML\bellAGtmp.xml
gml_nodes_lg.pl 182 newXML\bohrN.xml
gml_nodes_lg.pl 197 newXML\bornM.xml
gml_nodes_lg.pl 209 newXML\braggWSir.xml
gml_nodes_lg.pl 217 newXML\brattainW.xml
gml_nodes_lg.pl 218 newXML\braunKF.xml
gml_nodes_lg.pl 227 newXML\brewsterDSir.xml
gml_nodes_lg.pl 235 newXML\broglieLVPRde.xml
gml_nodes_lg.pl 254 newXML\buchanJ.xml
gml_nodes_lg.pl 275 newXML\byronGGLord.xml
gml_nodes_lg.pl 309 newXML\cassinifamily.xml
gml_nodes_lg.pl 379 newXML\communism.xml
gml_nodes_lg.pl 428 newXML\curieM.xml
gml_nodes_lg.pl 444 newXML\darwinC.xml
gml_nodes_lg.pl 445 newXML\darwinE.xml
gml_nodes_lg.pl 449 newXML\davyHSir.xml
gml_nodes_lg.pl 450 newXML\debussyC.xml
gml_nodes_lg.pl 460 newXML\descartesR.xml
gml_nodes_lg.pl 464 newXML\diaghilevS.xml
gml_nodes_lg.pl 516 newXML\eastmanG.xml
gml_nodes_lg.pl 518 newXML\edisonTA.xml
gml_nodes_lg.pl 524 newXML\einsteinA.xml
gml_nodes_lg.pl 529 newXML\electricmotortmp.xml
gml_nodes_lg.pl 531 newXML\electrolysistmp.xml
gml_nodes_lg.pl 532 newXML\electromagneticradiationtmp.xml
gml_nodes_lg.pl 533 newXML\electromagnetism.xml
gml_nodes_lg.pl 545 newXML\engelsF.xml
gml_nodes_lg.pl 553 newXML\eugenicstmp.xml
gml_nodes_lg.pl 559 newXML\evolution.xml
gml_nodes_lg.pl 565 newXML\faradayM.xml
gml_nodes_lg.pl 594 newXML\_follenK.xml
gml_nodes_lg.pl 609 newXML\franklinB.xml
gml_nodes_lg.pl 619 newXML\freudS.xml
gml_nodes_lg.pl 632 newXML\galileo.xml
gml_nodes_lg.pl 635 newXML\_gallFJ.xml
gml_nodes_lg.pl 637 newXML\galtonF.xml
gml_nodes_lg.pl 638 newXML\galvaniL.xml
gml_nodes_lg.pl 684 newXML\goddardRH.xml
gml_nodes_lg.pl 689 newXML\goetheJWvon.xml
gml_nodes_lg.pl 744 newXML\gyro.xml
gml_nodes_lg.pl 748 newXML\halesS.xml
gml_nodes_lg.pl 759 newXML\hamiltonWSir.xml
gml_nodes_lg.pl 787 newXML\heisenbergW.xml
gml_nodes_lg.pl 788 newXML\_helicopter.xml
gml_nodes_lg.pl 789 newXML\helmholtzHvon.xml
gml_nodes_lg.pl 802 newXML\herschelWSir.xml
gml_nodes_lg.pl 803 newXML\hertzH.xml
gml_nodes_lg.pl 804 newXML\herzlT.xml
gml_nodes_lg.pl 815 newXML\_hoffmannETA.xml
gml_nodes_lg.pl 855 newXML\hypnosis.xml
gml_nodes_lg.pl 858 newXML\inductiontmp.xml
gml_nodes_lg.pl 871 newXML\jamesH.xml
gml_nodes_lg.pl 876 newXML\_jeffersonTPres.xml
gml_nodes_lg.pl 899 newXML\kaleidoscope.xml
gml_nodes_lg.pl 959 newXML\langevinP.xml
gml_nodes_lg.pl 963 newXML\laser.xml
gml_nodes_lg.pl 970 newXML\lawrenceTE.xml
gml_nodes_lg.pl 981 newXML\leibnizG.xml
gml_nodes_lg.pl 983 newXML\leninVI.xml
gml_nodes_lg.pl 986 newXML\lessepsDde.xml
gml_nodes_lg.pl 991 newXML\lightbulb.xml
gml_nodes_lg.pl 1001 newXML\liquidfuelrockettmp.xml
gml_nodes_lg.pl 1004 newXML\lisztF.xml
gml_nodes_lg.pl 1038 newXML\machE.xml
gml_nodes_lg.pl 1039 newXML\machnumbertmp.xml
gml_nodes_lg.pl 1048 newXML\mahlerG.xml
gml_nodes_lg.pl 1061 newXML\maozedong.xml
gml_nodes_lg.pl 1062 newXML\marconiG.xml
gml_nodes_lg.pl 1076 newXML\marxK.xml
gml_nodes_lg.pl 1117 newXML\mesmerFA.xml
gml_nodes_lg.pl 1168 newXML\_mozartWA.xml
gml_nodes_lg.pl 1186 newXML\napoleon.xml
gml_nodes_lg.pl 1199 newXML\nehruJ.xml
gml_nodes_lg.pl 1201 newXML\nelsonH.xml
gml_nodes_lg.pl 1217 newXML\nipkowPG.xml
gml_nodes_lg.pl 1227 newXML\oerstedHC.xml
gml_nodes_lg.pl 1241 newXML\oscilloscopetmp.xml
gml_nodes_lg.pl 1317 newXML\planckM.xml
gml_nodes_lg.pl 1327 newXML\_poeEA.xml
gml_nodes_lg.pl 1350 newXML\psychoanalysis.xml
gml_nodes_lg.pl 1356 newXML\purjinkecellstmp.xml
gml_nodes_lg.pl 1357 newXML\purkinjeJE.xml
gml_nodes_lg.pl 1358 newXML\quantumphysicstmp.xml
gml_nodes_lg.pl 1361 newXML\_rachmaninovS.xml
gml_nodes_lg.pl 1363 newXML\radartmp.xml
gml_nodes_lg.pl 1364 newXML\radio.xml
gml_nodes_lg.pl 1365 newXML\radioactivitytmp.xml
gml_nodes_lg.pl 1383 newXML\reductionism.xml
gml_nodes_lg.pl 1387 newXML\relativity.xml
gml_nodes_lg.pl 1429 newXML\rooseveltFD.xml
gml_nodes_lg.pl 1447 newXML\rutherfordE.xml
gml_nodes_lg.pl 1464 newXML\schellingFWvon.xml
gml_nodes_lg.pl 1497 newXML\shawGB.xml
gml_nodes_lg.pl 1505 newXML\shockleyWB.xml
gml_nodes_lg.pl 1517 newXML\_sikorskyI.xml
gml_nodes_lg.pl 1545 newXML\somervilleM.xml
gml_nodes_lg.pl 1546 newXML\sonar.xml
gml_nodes_lg.pl 1548 newXML\soundonfilmtmp.xml
gml_nodes_lg.pl 1551 newXML\spaceflight.xml
gml_nodes_lg.pl 1553 newXML\spencerH.xml
gml_nodes_lg.pl 1556 newXML\sperryEA.xml
gml_nodes_lg.pl 1557 newXML\spinozaB.xml
gml_nodes_lg.pl 1560 newXML\_spurzheimJC.xml
gml_nodes_lg.pl 1563 newXML\stalin.xml
gml_nodes_lg.pl 1588 newXML\suezcanal.xml
gml_nodes_lg.pl 1598 newXML\swintonAA.xml
gml_nodes_lg.pl 1604 newXML\tchaikovskyP.xml
gml_nodes_lg.pl 1607 newXML\telephone.xml
gml_nodes_lg.pl 1614 newXML\teslaN.xml
gml_nodes_lg.pl 1648 newXML\transistortmp.xml
gml_nodes_lg.pl 1662 newXML\tv.xml
gml_nodes_lg.pl 1664 newXML\tykociner.xml
gml_nodes_lg.pl 1689 newXML\verdiG.xml
gml_nodes_lg.pl 1712 newXML\voltaA.xml
gml_nodes_lg.pl 1713 newXML\voltaireFMAde.xml
gml_nodes_lg.pl 1730 newXML\watsonWattR.xml
gml_nodes_lg.pl 1731 newXML\wattJ.xml
gml_nodes_lg.pl 1738 newXML\wedgwoodJ.xml
gml_nodes_lg.pl 1743 newXML\wellsHG.xml
gml_nodes_lg.pl 1748 newXML\westinghouse.xml
gml_nodes_lg.pl 1800 newXML\zionism.xml
gml_nodes_lg.pl 1806 newXML\zworykinVK.xml
