@echo off
node_ids.pl 95 newXML\bardeenJ.xml
node_ids.pl 114 newXML\_beaumarchaisPACde.xml
node_ids.pl 116 newXML\_beccariaC.xml
node_ids.pl 126 newXML\bellAGtmp.xml
node_ids.pl 182 newXML\bohrN.xml
node_ids.pl 197 newXML\bornM.xml
node_ids.pl 209 newXML\braggWSir.xml
node_ids.pl 217 newXML\brattainW.xml
node_ids.pl 218 newXML\braunKF.xml
node_ids.pl 227 newXML\brewsterDSir.xml
node_ids.pl 235 newXML\broglieLVPRde.xml
node_ids.pl 254 newXML\buchanJ.xml
node_ids.pl 275 newXML\byronGGLord.xml
node_ids.pl 309 newXML\cassinifamily.xml
node_ids.pl 379 newXML\communism.xml
node_ids.pl 428 newXML\curieM.xml
node_ids.pl 444 newXML\darwinC.xml
node_ids.pl 445 newXML\darwinE.xml
node_ids.pl 449 newXML\davyHSir.xml
node_ids.pl 450 newXML\debussyC.xml
node_ids.pl 460 newXML\descartesR.xml
node_ids.pl 464 newXML\diaghilevS.xml
node_ids.pl 516 newXML\eastmanG.xml
node_ids.pl 518 newXML\edisonTA.xml
node_ids.pl 524 newXML\einsteinA.xml
node_ids.pl 529 newXML\electircMotor.xml
node_ids.pl 531 newXML\electrolysistmp.xml
node_ids.pl 532 newXML\electromagneticradiationtmp.xml
node_ids.pl 533 newXML\electromagnetism.xml
node_ids.pl 545 newXML\engelsF.xml
node_ids.pl 553 newXML\eugenicstmp.xml
node_ids.pl 559 newXML\evolution.xml
node_ids.pl 565 newXML\faradayM.xml
node_ids.pl 594 newXML\_follenK.xml
node_ids.pl 609 newXML\franklinB.xml
node_ids.pl 619 newXML\freudS.xml
node_ids.pl 632 newXML\galileo.xml
node_ids.pl 635 newXML\_gallFJ.xml
node_ids.pl 637 newXML\galtonF.xml
node_ids.pl 638 newXML\galvaniL.xml
node_ids.pl 684 newXML\goddardRH.xml
node_ids.pl 689 newXML\goetheJWvon.xml
node_ids.pl 744 newXML\gyro.xml
node_ids.pl 748 newXML\halesS.xml
node_ids.pl 759 newXML\hamiltonWSir.xml
node_ids.pl 787 newXML\heisenbergW.xml
node_ids.pl 788 newXML\_helicopter.xml
node_ids.pl 789 newXML\helmholtzHvon.xml
node_ids.pl 802 newXML\herschelWSir.xml
node_ids.pl 803 newXML\hertzH.xml
node_ids.pl 804 newXML\herzlT.xml
node_ids.pl 815 newXML\_hoffmannETA.xml
node_ids.pl 855 newXML\hypnosis.xml
node_ids.pl 858 newXML\inductiontmp.xml
node_ids.pl 871 newXML\jamesH.xml
node_ids.pl 876 newXML\_jeffersonTPres.xml
node_ids.pl 899 newXML\kaleidoscope.xml
node_ids.pl 959 newXML\langevinP.xml
node_ids.pl 963 newXML\laser.xml
node_ids.pl 970 newXML\lawrenceTE.xml
node_ids.pl 981 newXML\leibnizG.xml
node_ids.pl 983 newXML\leninVI.xml
node_ids.pl 986 newXML\lessepsDde.xml
node_ids.pl 991 newXML\lightbulb.xml
node_ids.pl 1001 newXML\liquidfuelrockettmp.xml
node_ids.pl 1004 newXML\lisztF.xml
node_ids.pl 1038 newXML\machE.xml
node_ids.pl 1039 newXML\machnumbertmp.xml
node_ids.pl 1048 newXML\mahlerG.xml
node_ids.pl 1061 newXML\maozedong.xml
node_ids.pl 1062 newXML\marconiG.xml
node_ids.pl 1076 newXML\marxK.xml
node_ids.pl 1117 newXML\mesmerFA.xml
node_ids.pl 1168 newXML\_mozartWA.xml
node_ids.pl 1186 newXML\napoleon.xml
node_ids.pl 1199 newXML\nehruJ.xml
node_ids.pl 1201 newXML\nelsonH.xml
node_ids.pl 1217 newXML\nipkowPG.xml
node_ids.pl 1227 newXML\oerstedHC.xml
node_ids.pl 1241 newXML\oscilloscopetmp.xml
node_ids.pl 1317 newXML\planckM.xml
node_ids.pl 1327 newXML\_poeEA.xml
node_ids.pl 1350 newXML\psychoanalysis.xml
node_ids.pl 1356 newXML\purjinkecellstmp.xml
node_ids.pl 1357 newXML\purkinjeJE.xml
node_ids.pl 1358 newXML\quantumphysicstmp.xml
node_ids.pl 1361 newXML\_rachmaninovS.xml
node_ids.pl 1363 newXML\radartmp.xml
node_ids.pl 1364 newXML\radio.xml
node_ids.pl 1365 newXML\radioactivitytmp.xml
node_ids.pl 1383 newXML\reductionism.xml
node_ids.pl 1387 newXML\relativity.xml
node_ids.pl 1429 newXML\rooseveltFD.xml
node_ids.pl 1447 newXML\rutherfordE.xml
node_ids.pl 1464 newXML\schellingFWvon.xml
node_ids.pl 1497 newXML\shawGB.xml
node_ids.pl 1505 newXML\shockleyWB.xml
node_ids.pl 1517 newXML\_sikorskyI.xml
node_ids.pl 1545 newXML\somervilleM.xml
node_ids.pl 1546 newXML\sonar.xml
node_ids.pl 1548 newXML\soundonfilmtmp.xml
node_ids.pl 1551 newXML\spaceflight.xml
node_ids.pl 1553 newXML\spencerH.xml
node_ids.pl 1556 newXML\sperryEA.xml
node_ids.pl 1557 newXML\spinozaB.xml
node_ids.pl 1560 newXML\_spurzheimJC.xml
node_ids.pl 1563 newXML\stalin.xml
node_ids.pl 1588 newXML\suezcanal.xml
node_ids.pl 1598 newXML\swintonAA.xml
node_ids.pl 1604 newXML\tchaikovskyP.xml
node_ids.pl 1607 newXML\telephone.xml
node_ids.pl 1614 newXML\teslaN.xml
node_ids.pl 1648 newXML\transistortmp.xml
node_ids.pl 1662 newXML\tv.xml
node_ids.pl 1664 newXML\tykociner.xml
node_ids.pl 1689 newXML\verdiG.xml
node_ids.pl 1712 newXML\voltaA.xml
node_ids.pl 1713 newXML\voltaireFMAde.xml
node_ids.pl 1730 newXML\watsonWattR.xml
node_ids.pl 1731 newXML\wattJ.xml
node_ids.pl 1738 newXML\wedgwoodJ.xml
node_ids.pl 1743 newXML\wellsHG.xml
node_ids.pl 1748 newXML\westinghouse.xml
node_ids.pl 1800 newXML\zionism.xml
node_ids.pl 1806 newXML\zworykinVK.xml
