/*
 * $Header: /zpool01/javanet/scm/svn/tmp/cvs2svn/lg3d-incubator/src/classes/org/jdesktop/lg3d/apps/kwebdemo1/singletons/EdgeData.java,v 1.2 2005-06-24 19:57:13 paulby Exp $
 * $Date: 2005-06-24 19:57:13 $
 *
 * Joint Copyright (c) 2005 by
 *   James A. Zaun, Consultant,
 *   The Burke Institute,
 *   Sun Microsystems, Inc.
 * ALL RIGHTS RESERVED.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 */

package org.jdesktop.lg3d.apps.kwebdemo1.singletons;

/*
 * I prefer to explicitly show each class import rather use the '*' wildcard.
 * While it is more typing, the reader can see exactly where each class is
 * coming from, and it avoids software version skew problems were a class name
 * may be added to a package in the future that is already in use by another
 * package thus causing a naming conflict when using wildcards.  -jim zaun  
 */
import java.util.Hashtable;
import java.util.Enumeration;
import java.lang.Integer;

import org.jdesktop.lg3d.apps.kwebdemo1.edges.*;


/**
 * James Burke's Knowledge Web graph edge data.
 * 
 * <p style="color: red; font-weight: bold">Note: This class is autogenerated
 * from a Perl 5.8 script, <code>create_EdgeData.pl</code> located in the
 * <code>tools</code> subdirectory.  DO NOT EDIT THIS CODE DIRECTLY.</p>
 * 
 * <p>This is only a small portion of the complete KWeb graph for
 * the purposes of this demo only.  The full dataset is copyrighted under
 * a different copyright agreement. Only this portion is used by permission of
 * the Burke Institute and put under the GNU General Public License.</p>
 * 
 * <p>This class is normally used in conjunction with the
 * {@link NodeData NodeData} class which contains the graph node details
 * that the edges in this Class create associations between.</p>
 *
 * @see org.jdesktop.lg3d.apps.kwebdemo1.edges.BasicEdge
 * @see org.jdesktop.lg3d.apps.kwebdemo1.edges.DisplayedEdge
 * @see org.jdesktop.lg3d.apps.kwebdemo1.edges.JourneyEdge
 *
 * @author Jim Zaun &lt;jz-lg@zaun.com&gt; (a.k.a. &lt;zaun@acm.org&gt;)
 * @version $Revision: 1.2 $
 * @since JDK 1.5.0, Java3D 1.4.0, lg3d-{core,demo,incubator} 0.7.0
 */
public class EdgeData
{
  static private EdgeData edgeData = null;
  private Hashtable<String,BasicEdge> edgeTable =
    new Hashtable<String,BasicEdge>(1023);

  /*
   * The contructor is hidden so the class can only be invoked by
   * getInstance().
   */
  private EdgeData()
  {
    BasicEdge edge = null;
    edge = new DisplayedEdge(95, 1505,
                       "Bardeen%2C+John",
                       "collaborated with",
                       "Shockley%2C+William+Bradford");
    edgeTable.put("95-1505", edge);
    edge = new DisplayedEdge(95, 217,
                       "Bardeen%2C+John",
                       "collaborated with",
                       "Brattain%2C+Walter+Houser");
    edgeTable.put("95-217", edge);
    edge = new JourneyEdgeB(114, 876,
                       "Beaumarchais%2C+Caron+de",
                       "supported by",
                       "Jefferson%2C+Pres.+Thomas");
    edgeTable.put("95-217", edge);
    edge = new BasicEdge(114, 1168,
                       "Beaumarchais%2C+Caron+de",
                       "work adapted by",
                       "Mozart%2C+Wolfgang+Amadeus");
    edgeTable.put("114-1168", edge);
    edge = new DisplayedEdge(114, 1713,
                       "Beaumarchais%2C+Caron+de",
                       "admirer of",
                       "Voltaire%2C+Francois-Marie+Arouet+de");
    edgeTable.put("114-1713", edge);
    edge = new DisplayedEdge(116, 1713,
                       "Beccaria%2C+Cesare",
                       "a fan was",
                       "Voltaire%2C+Francois-Marie+Arouet+de");
    edgeTable.put("116-1713", edge);
    edge = new BasicEdge(116, 876,
                       "Beccaria%2C+Cesare",
                       "influenced",
                       "Jefferson%2C+Pres.+Thomas");
    edgeTable.put("116-876", edge);
    edge = new JourneyEdgeD(116, 635,
                       "Beccaria%2C+Cesare",
                       "his work related to",
                       "Gall%2C+Franz+Josef");
    edgeTable.put("116-876", edge);
    edge = new DisplayedEdge(126, 1607,
                       "Bell%2C+Alexander+Graham",
                       "invented",
                       "Telephone");
    edgeTable.put("126-1607", edge);
    edge = new DisplayedEdge(126, 518,
                       "Bell%2C+Alexander+Graham",
                       "improved phonograph of",
                       "Edison%2C+Thomas+Alva");
    edgeTable.put("126-518", edge);
    edge = new DisplayedEdge(126, 684,
                       "Bell%2C+Alexander+Graham",
                       "visited",
                       "Goddard%2C+Robert+Hutchings");
    edgeTable.put("126-684", edge);
    edge = new DisplayedEdge(182, 1447,
                       "Bohr%2C+Niels+Henrik+David",
                       "encouraged by",
                       "Rutherford%2C+Ernest");
    edgeTable.put("182-1447", edge);
    edge = new DisplayedEdge(182, 1317,
                       "Bohr%2C+Niels+Henrik+David",
                       "used theory of",
                       "Planck%2C+Max");
    edgeTable.put("182-1317", edge);
    edge = new DisplayedEdge(182, 787,
                       "Bohr%2C+Niels+Henrik+David",
                       "his work developed by",
                       "Heisenberg%2C+Werner+Karl");
    edgeTable.put("182-787", edge);
    edge = new DisplayedEdge(182, 524,
                       "Bohr%2C+Niels+Henrik+David",
                       "opposed by",
                       "Einstein%2C+Albert");
    edgeTable.put("182-524", edge);
    edge = new DisplayedEdge(182, 197,
                       "Bohr%2C+Niels+Henrik+David",
                       "work related to",
                       "Born%2C+Max");
    edgeTable.put("182-197", edge);
    edge = new DisplayedEdge(197, 524,
                       "Born%2C+Max",
                       "work related to",
                       "Einstein%2C+Albert");
    edgeTable.put("197-524", edge);
    edge = new DisplayedEdge(197, 1317,
                       "Born%2C+Max",
                       "replaced",
                       "Planck%2C+Max");
    edgeTable.put("197-1317", edge);
    edge = new BasicEdge(197, 182,
                       "Born%2C+Max",
                       "influenced by",
                       "Bohr%2C+Niels+Henrik+David");
    edgeTable.put("197-182", edge);
    edge = new DisplayedEdge(197, 787,
                       "Born%2C+Max",
                       "assisted by",
                       "Heisenberg%2C+Werner+Karl");
    edgeTable.put("197-787", edge);
    edge = new DisplayedEdge(209, 428,
                       "Bragg%2C+Sir+William+Henry",
                       "influenced by",
                       "Curie%2C+Marie");
    edgeTable.put("209-428", edge);
    edge = new DisplayedEdge(209, 1447,
                       "Bragg%2C+Sir+William+Henry",
                       "encouraged by",
                       "Rutherford%2C+Ernest");
    edgeTable.put("209-1447", edge);
    edge = new DisplayedEdge(217, 1505,
                       "Brattain%2C+Walter+Houser",
                       "collaborated with",
                       "Shockley%2C+William+Bradford");
    edgeTable.put("217-1505", edge);
    edge = new BasicEdge(217, 95,
                       "Brattain%2C+Walter+Houser",
                       "collaborated with",
                       "Bardeen%2C+John");
    edgeTable.put("217-95", edge);
    edge = new DisplayedEdge(218, 803,
                       "Braun%2C+Karl+Ferdinand",
                       "was succeeded by",
                       "Hertz%2C+Heinrich+Rudolf");
    edgeTable.put("218-803", edge);
    edge = new DisplayedEdge(218, 1062,
                       "Braun%2C+Karl+Ferdinand",
                       "inspired by",
                       "Marconi%2C+Guglielmo");
    edgeTable.put("218-1062", edge);
    edge = new DisplayedEdge(218, 1505,
                       "Braun%2C+Karl+Ferdinand",
                       "anticipated",
                       "Shockley%2C+William+Bradford");
    edgeTable.put("218-1505", edge);
    edge = new DisplayedEdge(218, 95,
                       "Braun%2C+Karl+Ferdinand",
                       "anticipated",
                       "Bardeen%2C+John");
    edgeTable.put("218-95", edge);
    edge = new DisplayedEdge(218, 217,
                       "Braun%2C+Karl+Ferdinand",
                       "anticipated",
                       "Brattain%2C+Walter+Houser");
    edgeTable.put("218-217", edge);
    edge = new DisplayedEdge(218, 1598,
                       "Braun%2C+Karl+Ferdinand",
                       "work related to",
                       "Swinton%2C+Alan+Archibald+Campbell");
    edgeTable.put("218-1598", edge);
    edge = new DisplayedEdge(218, 1806,
                       "Braun%2C+Karl+Ferdinand",
                       "work related to",
                       "Zworykin%2C+Vladimir+Kosma");
    edgeTable.put("218-1806", edge);
    edge = new DisplayedEdge(227, 789,
                       "Brewster%2C+Sir+David",
                       "superseded by",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("227-789", edge);
    edge = new DisplayedEdge(227, 428,
                       "Brewster%2C+Sir+David",
                       "work aided",
                       "Curie%2C+Marie");
    edgeTable.put("227-428", edge);
    edge = new DisplayedEdge(235, 1317,
                       "Broglie%2C+Louis%2C+Duke+de",
                       "influenced by",
                       "Planck%2C+Max");
    edgeTable.put("235-1317", edge);
    edge = new DisplayedEdge(235, 524,
                       "Broglie%2C+Louis%2C+Duke+de",
                       "influenced by",
                       "Einstein%2C+Albert");
    edgeTable.put("235-524", edge);
    edge = new DisplayedEdge(235, 959,
                       "Broglie%2C+Louis%2C+Duke+de",
                       "his brother hired",
                       "Langevin%2C+Paul");
    edgeTable.put("235-959", edge);
    edge = new DisplayedEdge(254, 871,
                       "Buchan%2C+John",
                       "a pal of",
                       "James%2C+Henry");
    edgeTable.put("254-871", edge);
    edge = new DisplayedEdge(309, 460,
                       "Cassini+family",
                       "supported theory of",
                       "Descartes%2C+Rene");
    edgeTable.put("309-460", edge);
    edge = new DisplayedEdge(379, 1076,
                       "Communism",
                       "co- founded by",
                       "Marx%2C+Karl");
    edgeTable.put("379-1076", edge);
    edge = new DisplayedEdge(379, 545,
                       "Communism",
                       "co-founded by",
                       "Engels%2C+Friedrich");
    edgeTable.put("379-545", edge);
    edge = new BasicEdge(428, 227,
                       "Curie%2C+Marie",
                       "used work of",
                       "Brewster%2C+Sir+David");
    edgeTable.put("428-227", edge);
    edge = new DisplayedEdge(428, 959,
                       "Curie%2C+Marie",
                       "affair with",
                       "Langevin%2C+Paul");
    edgeTable.put("428-959", edge);
    edge = new DisplayedEdge(428, 1447,
                       "Curie%2C+Marie",
                       "influenced by",
                       "Rutherford%2C+Ernest");
    edgeTable.put("428-1447", edge);
    edge = new DisplayedEdge(428, 1664,
                       "Curie%2C+Marie",
                       "work related to",
                       "Tykociner%2C+Joseph");
    edgeTable.put("428-1664", edge);
    edge = new BasicEdge(428, 209,
                       "Curie%2C+Marie",
                       "influenced",
                       "Bragg%2C+Sir+William+Henry");
    edgeTable.put("428-209", edge);
    edge = new DisplayedEdge(444, 1553,
                       "Darwin%2C+Charles+Robert",
                       "work related to",
                       "Spencer%2C+Herbert");
    edgeTable.put("444-1553", edge);
    edge = new DisplayedEdge(444, 1738,
                       "Darwin%2C+Charles+Robert",
                       "grandfather was",
                       "Wedgwood%2C+Josiah");
    edgeTable.put("444-1738", edge);
    edge = new DisplayedEdge(445, 637,
                       "Darwin%2C+Erasmus",
                       "related to",
                       "Galton%2C+Sir+Francis");
    edgeTable.put("445-637", edge);
    edge = new DisplayedEdge(445, 1553,
                       "Darwin%2C+Erasmus",
                       "shared view of",
                       "Spencer%2C+Herbert");
    edgeTable.put("445-1553", edge);
    edge = new DisplayedEdge(449, 275,
                       "Davy%2C+Sir+Humphry",
                       "visited",
                       "Byron%2C+George+Gordon");
    edgeTable.put("449-275", edge);
    edge = new DisplayedEdge(449, 1545,
                       "Davy%2C+Sir+Humphry",
                       "knew",
                       "Somerville%2C+Mary");
    edgeTable.put("449-1545", edge);
    edge = new DisplayedEdge(450, 1604,
                       "Debussy%2C+Achille-Claude",
                       "shared patron with",
                       "Tchaikovsky%2C+Peter+Ilich");
    edgeTable.put("450-1604", edge);
    edge = new DisplayedEdge(450, 1004,
                       "Debussy%2C+Achille-Claude",
                       "played for",
                       "Liszt%2C+Franz");
    edgeTable.put("450-1004", edge);
    edge = new DisplayedEdge(450, 464,
                       "Debussy%2C+Achille-Claude",
                       "wrote for",
                       "Diaghilev%2C+Sergei+Pavlovich");
    edgeTable.put("450-464", edge);
    edge = new DisplayedEdge(450, 1327,
                       "Debussy%2C+Achille-Claude",
                       "influenced by",
                       "Poe%2C+Edgar+Allan");
    edgeTable.put("450-1327", edge);
    edge = new DisplayedEdge(460, 981,
                       "Descartes%2C+Rene",
                       "laid ground for",
                       "Leibniz%2C+Gottfried+Wilhelm");
    edgeTable.put("460-981", edge);
    edge = new DisplayedEdge(460, 638,
                       "Descartes%2C+Rene",
                       "influenced",
                       "Galvani%2C+Luigi");
    edgeTable.put("460-638", edge);
    edge = new BasicEdge(460, 309,
                       "Descartes%2C+Rene",
                       "opposed by",
                       "Cassini+family");
    edgeTable.put("460-309", edge);
    edge = new DisplayedEdge(516, 518,
                       "Eastman%2C+George",
                       "provided film for",
                       "Edison%2C+Thomas+Alva");
    edgeTable.put("516-518", edge);
    edge = new BasicEdge(518, 126,
                       "Edison%2C+Thomas+Alva",
                       "rival telephone by",
                       "Bell%2C+Alexander+Graham");
    edgeTable.put("518-126", edge);
    edge = new DisplayedEdge(518, 1614,
                       "Edison%2C+Thomas+Alva",
                       "assistant was",
                       "Tesla%2C+Nikola");
    edgeTable.put("518-1614", edge);
    edge = new BasicEdge(518, 516,
                       "Edison%2C+Thomas+Alva",
                       "collaborated with",
                       "Eastman%2C+George");
    edgeTable.put("518-516", edge);
    edge = new DisplayedEdge(518, 1556,
                       "Edison%2C+Thomas+Alva",
                       "work related to",
                       "Sperry%2C+Elmer+Ambrose");
    edgeTable.put("518-1556", edge);
    edge = new DisplayedEdge(518, 1748,
                       "Edison%2C+Thomas+Alva",
                       "rival was",
                       "Westinghouse");
    edgeTable.put("518-1748", edge);
    edge = new DisplayedEdge(524, 803,
                       "Einstein%2C+Albert",
                       "studied work of",
                       "Hertz%2C+Heinrich+Rudolf");
    edgeTable.put("524-803", edge);
    edge = new DisplayedEdge(524, 1317,
                       "Einstein%2C+Albert",
                       "drew on work of",
                       "Planck%2C+Max");
    edgeTable.put("524-1317", edge);
    edge = new BasicEdge(524, 235,
                       "Einstein%2C+Albert",
                       "inspired",
                       "Broglie%2C+Louis%2C+Duke+de");
    edgeTable.put("524-235", edge);
    edge = new DisplayedEdge(524, 787,
                       "Einstein%2C+Albert",
                       "rejected view of",
                       "Heisenberg%2C+Werner+Karl");
    edgeTable.put("524-787", edge);
    edge = new BasicEdge(524, 182,
                       "Einstein%2C+Albert",
                       "knew",
                       "Bohr%2C+Niels+Henrik+David");
    edgeTable.put("524-182", edge);
    edge = new BasicEdge(524, 197,
                       "Einstein%2C+Albert",
                       "a pal of",
                       "Born%2C+Max");
    edgeTable.put("524-197", edge);
    edge = new DisplayedEdge(524, 959,
                       "Einstein%2C+Albert",
                       "nearly anticipated by",
                       "Langevin%2C+Paul");
    edgeTable.put("524-959", edge);
    edge = new DisplayedEdge(524, 789,
                       "Einstein%2C+Albert",
                       "influenced by",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("524-789", edge);
    edge = new DisplayedEdge(524, 1447,
                       "Einstein%2C+Albert",
                       "knew",
                       "Rutherford%2C+Ernest");
    edgeTable.put("524-1447", edge);
    edge = new DisplayedEdge(529, 1614,
                       "electric+motor",
                       "invented by",
                       "Tesla%2C+Nikola");
    edgeTable.put("529-1614", edge);
    edge = new DisplayedEdge(531, 565,
                       "Electrolysis",
                       "pioneered by",
                       "Faraday%2C+Michael");
    edgeTable.put("531-565", edge);
    edge = new DisplayedEdge(532, 803,
                       "Electromagnetic+radiation",
                       "discovered by",
                       "Hertz%2C+Heinrich+Rudolf");
    edgeTable.put("532-803", edge);
    edge = new DisplayedEdge(533, 1227,
                       "electromagnetism",
                       "discovered by",
                       "Oersted%2C+Hans+Christian");
    edgeTable.put("533-1227", edge);
    edge = new DisplayedEdge(545, 1464,
                       "Engels%2C+Friedrich",
                       "taught by",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("545-1464", edge);
    edge = new DisplayedEdge(545, 1076,
                       "Engels%2C+Friedrich",
                       "collaborated with",
                       "Marx%2C+Karl");
    edgeTable.put("545-1076", edge);
    edge = new DisplayedEdge(553, 637,
                       "Eugenics",
                       "pioneered by",
                       "Galton%2C+Sir+Francis");
    edgeTable.put("553-637", edge);
    edge = new DisplayedEdge(559, 444,
                       "Evolution%2C+theory+of",
                       "developed by",
                       "Darwin%2C+Charles+Robert");
    edgeTable.put("559-444", edge);
    edge = new DisplayedEdge(565, 449,
                       "Faraday%2C+Michael",
                       "assistant to",
                       "Davy%2C+Sir+Humphry");
    edgeTable.put("565-449", edge);
    edge = new DisplayedEdge(565, 1712,
                       "Faraday%2C+Michael",
                       "met",
                       "Volta%2C+Alessandro");
    edgeTable.put("565-1712", edge);
    edge = new DisplayedEdge(565, 1227,
                       "Faraday%2C+Michael",
                       "picked up on work of",
                       "Oersted%2C+Hans+Christian");
    edgeTable.put("565-1227", edge);
    edge = new DisplayedEdge(565, 1545,
                       "Faraday%2C+Michael",
                       "knew",
                       "Somerville%2C+Mary");
    edgeTable.put("565-1545", edge);
    edge = new JourneyEdgeG(594, 815,
                       "Follen%2C+Karl",
                       "investigated by",
                       "Hoffmann%2C+Ernst+Theodor+Amadeus");
    edgeTable.put("565-1545", edge);
    edge = new BasicEdge(594, 1560,
                       "Follen%2C+Karl",
                       "gave funeral oration for",
                       "Spurzheim%2C+Johann");
    edgeTable.put("594-1560", edge);
    edge = new DisplayedEdge(609, 876,
                       "Franklin%2C+Benjamin",
                       "worked with",
                       "Jefferson%2C+Pres.+Thomas");
    edgeTable.put("609-876", edge);
    edge = new DisplayedEdge(609, 1713,
                       "Franklin%2C+Benjamin",
                       "a pal of",
                       "Voltaire%2C+Francois-Marie+Arouet+de");
    edgeTable.put("609-1713", edge);
    edge = new DisplayedEdge(609, 1117,
                       "Franklin%2C+Benjamin",
                       "critiqued",
                       "Mesmer%2C+Franz+Anton");
    edgeTable.put("609-1117", edge);
    edge = new DisplayedEdge(609, 638,
                       "Franklin%2C+Benjamin",
                       "influenced",
                       "Galvani%2C+Luigi");
    edgeTable.put("609-638", edge);
    edge = new DisplayedEdge(609, 460,
                       "Franklin%2C+Benjamin",
                       "influenced by",
                       "Descartes%2C+Rene");
    edgeTable.put("609-460", edge);
    edge = new DisplayedEdge(609, 1712,
                       "Franklin%2C+Benjamin",
                       "influenced by",
                       "Volta%2C+Alessandro");
    edgeTable.put("609-1712", edge);
    edge = new DisplayedEdge(619, 789,
                       "Freud%2C+Sigmund",
                       "influenced by",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("619-789", edge);
    edge = new DisplayedEdge(619, 637,
                       "Freud%2C+Sigmund",
                       "anticipated by",
                       "Galton%2C+Sir+Francis");
    edgeTable.put("619-637", edge);
    edge = new DisplayedEdge(619, 1048,
                       "Freud%2C+Sigmund",
                       "a patient was",
                       "Mahler%2C+Gustav");
    edgeTable.put("619-1048", edge);
    edge = new DisplayedEdge(632, 227,
                       "Galilei%2C+Galileo",
                       "biography written by",
                       "Brewster%2C+Sir+David");
    edgeTable.put("632-227", edge);
    edge = new DisplayedEdge(632, 309,
                       "Galilei%2C+Galileo",
                       "work developed by",
                       "Cassini+family");
    edgeTable.put("632-309", edge);
    edge = new DisplayedEdge(632, 460,
                       "Galilei%2C+Galileo",
                       "influenced",
                       "Descartes%2C+Rene");
    edgeTable.put("632-460", edge);
    edge = new DisplayedEdge(635, 460,
                       "Gall%2C+Franz+Josef",
                       "disagreed with theory of",
                       "Descartes%2C+Rene");
    edgeTable.put("635-460", edge);
    edge = new JourneyEdgeE(635, 1560,
                       "Gall%2C+Franz+Josef",
                       "his partner was",
                       "Spurzheim%2C+Johann");
    edgeTable.put("635-460", edge);
    edge = new BasicEdge(635, 116,
                       "Gall%2C+Franz+Josef",
                       "followed up work of",
                       "Beccaria%2C+Cesare");
    edgeTable.put("635-116", edge);
    edge = new DisplayedEdge(635, 1076,
                       "Gall%2C+Franz+Josef",
                       "follower was",
                       "Marx%2C+Karl");
    edgeTable.put("635-1076", edge);
    edge = new BasicEdge(637, 445,
                       "Galton%2C+Sir+Francis",
                       "grandfather was",
                       "Darwin%2C+Erasmus");
    edgeTable.put("637-445", edge);
    edge = new DisplayedEdge(637, 1553,
                       "Galton%2C+Sir+Francis",
                       "collaborated with",
                       "Spencer%2C+Herbert");
    edgeTable.put("637-1553", edge);
    edge = new BasicEdge(637, 619,
                       "Galton%2C+Sir+Francis",
                       "anticipated",
                       "Freud%2C+Sigmund");
    edgeTable.put("637-619", edge);
    edge = new DisplayedEdge(638, 1712,
                       "Galvani%2C+Luigi",
                       "theory disproved by",
                       "Volta%2C+Alessandro");
    edgeTable.put("638-1712", edge);
    edge = new DisplayedEdge(638, 1464,
                       "Galvani%2C+Luigi",
                       "work related to",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("638-1464", edge);
    edge = new DisplayedEdge(638, 1117,
                       "Galvani%2C+Luigi",
                       "work related to",
                       "Mesmer%2C+Franz+Anton");
    edgeTable.put("638-1117", edge);
    edge = new BasicEdge(684, 126,
                       "Goddard%2C+Robert+Hutchings",
                       "visited",
                       "Bell%2C+Alexander+Graham");
    edgeTable.put("684-126", edge);
    edge = new DisplayedEdge(689, 1168,
                       "Goethe%2C+Johann+Wolfgang+von",
                       "poems set to music by",
                       "Mozart%2C+Wolfgang+Amadeus");
    edgeTable.put("689-1168", edge);
    edge = new DisplayedEdge(689, 1464,
                       "Goethe%2C+Johann+Wolfgang+von",
                       "knew",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("689-1464", edge);
    edge = new DisplayedEdge(744, 1556,
                       "gyroscope",
                       "invented by",
                       "Sperry%2C+Elmer+Ambrose");
    edgeTable.put("744-1556", edge);
    edge = new DisplayedEdge(748, 638,
                       "Hales%2C+Stephen",
                       "?",
                       "Galvani%2C+Luigi");
    edgeTable.put("748-638", edge);
    edge = new DisplayedEdge(759, 689,
                       "Hamilton%2C+Sir+William",
                       "visited by",
                       "Goethe%2C+Johann+Wolfgang+von");
    edgeTable.put("759-689", edge);
    edge = new BasicEdge(787, 182,
                       "Heisenberg%2C+Werner+Karl",
                       "developed work by",
                       "Bohr%2C+Niels+Henrik+David");
    edgeTable.put("787-182", edge);
    edge = new DisplayedEdge(787, 1317,
                       "Heisenberg%2C+Werner+Karl",
                       "work related to",
                       "Planck%2C+Max");
    edgeTable.put("787-1317", edge);
    edge = new BasicEdge(787, 197,
                       "Heisenberg%2C+Werner+Karl",
                       "collaborated with",
                       "Born%2C+Max");
    edgeTable.put("787-197", edge);
    edge = new BasicEdge(787, 524,
                       "Heisenberg%2C+Werner+Karl",
                       "theory rejected by",
                       "Einstein%2C+Albert");
    edgeTable.put("787-524", edge);
    edge = new BasicEdge(788, 1517,
                       "helicopter",
                       "first developed by",
                       "Sikorsky%2C+Igor+Ivanovich");
    edgeTable.put("788-1517", edge);
    edge = new BasicEdge(789, 524,
                       "Helmholtz%2C+Hermann+von",
                       "laid basis for work of",
                       "Einstein%2C+Albert");
    edgeTable.put("789-524", edge);
    edge = new DisplayedEdge(789, 803,
                       "Helmholtz%2C+Hermann+von",
                       "taught",
                       "Hertz%2C+Heinrich+Rudolf");
    edgeTable.put("789-803", edge);
    edge = new DisplayedEdge(789, 565,
                       "Helmholtz%2C+Hermann+von",
                       "influenced by",
                       "Faraday%2C+Michael");
    edgeTable.put("789-565", edge);
    edge = new BasicEdge(789, 227,
                       "Helmholtz%2C+Hermann+von",
                       "superseded work of",
                       "Brewster%2C+Sir+David");
    edgeTable.put("789-227", edge);
    edge = new BasicEdge(789, 619,
                       "Helmholtz%2C+Hermann+von",
                       "influenced",
                       "Freud%2C+Sigmund");
    edgeTable.put("789-619", edge);
    edge = new DisplayedEdge(789, 1217,
                       "Helmholtz%2C+Hermann+von",
                       "taught",
                       "Nipkow%2C+Paul+Gottlieb");
    edgeTable.put("789-1217", edge);
    edge = new DisplayedEdge(802, 309,
                       "Herschel%2C+Sir+William",
                       "visited by",
                       "Cassini+family");
    edgeTable.put("802-309", edge);
    edge = new BasicEdge(803, 789,
                       "Hertz%2C+Heinrich+Rudolf",
                       "assistant to",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("803-789", edge);
    edge = new BasicEdge(803, 532,
                       "Hertz%2C+Heinrich+Rudolf",
                       "discovered",
                       "Electromagnetic+radiation");
    edgeTable.put("803-532", edge);
    edge = new DisplayedEdge(803, 1062,
                       "Hertz%2C+Heinrich+Rudolf",
                       "made possible work of",
                       "Marconi%2C+Guglielmo");
    edgeTable.put("803-1062", edge);
    edge = new BasicEdge(803, 524,
                       "Hertz%2C+Heinrich+Rudolf",
                       "studied by",
                       "Einstein%2C+Albert");
    edgeTable.put("803-524", edge);
    edge = new DisplayedEdge(804, 986,
                       "Herzl%2C+Theodor",
                       "hero was",
                       "Lesseps%2C+Ferdinand%2C+Vicomte+de");
    edgeTable.put("804-986", edge);
    edge = new DisplayedEdge(815, 1168,
                       "Hoffmann%2C+Ernst+Theodor+Amadeus",
                       "inspired by",
                       "Mozart%2C+Wolfgang+Amadeus");
    edgeTable.put("815-1168", edge);
    edge = new JourneyEdgeH(815, 1327,
                       "Hoffmann%2C+Ernst+Theodor+Amadeus",
                       "influenced",
                       "Poe%2C+Edgar+Allan");
    edgeTable.put("815-1168", edge);
    edge = new BasicEdge(815, 594,
                       "Hoffmann%2C+Ernst+Theodor+Amadeus",
                       "investigated",
                       "Follen%2C+Karl");
    edgeTable.put("815-594", edge);
    edge = new DisplayedEdge(855, 1117,
                       "Hypnosis",
                       "first investigated by",
                       "Mesmer%2C+Franz+Anton");
    edgeTable.put("855-1117", edge);
    edge = new DisplayedEdge(858, 565,
                       "Induction",
                       "discovered by",
                       "Faraday%2C+Michael");
    edgeTable.put("858-565", edge);
    edge = new DisplayedEdge(871, 1497,
                       "James%2C+Henry",
                       "good review from",
                       "Shaw%2C+George+Bernard");
    edgeTable.put("871-1497", edge);
    edge = new DisplayedEdge(871, 1743,
                       "James%2C+Henry",
                       "neighbor was",
                       "Wells%2C+Herbert+George");
    edgeTable.put("871-1743", edge);
    edge = new BasicEdge(876, 609,
                       "Jefferson%2C+Pres.+Thomas",
                       "worked with",
                       "Franklin%2C+Benjamin");
    edgeTable.put("876-609", edge);
    edge = new DisplayedEdge(876, 1731,
                       "Jefferson%2C+Pres.+Thomas",
                       "met partner of",
                       "Watt%2C+James");
    edgeTable.put("876-1731", edge);
    edge = new JourneyEdgeC(876, 116,
                       "Jefferson%2C+Pres.+Thomas",
                       "influenced by",
                       "Beccaria%2C+Cesare");
    edgeTable.put("876-1731", edge);
    edge = new BasicEdge(876, 114,
                       "Jefferson%2C+Pres.+Thomas",
                       "supported",
                       "Beaumarchais%2C+Caron+de");
    edgeTable.put("876-114", edge);
    edge = new DisplayedEdge(899, 227,
                       "kaleidoscope",
                       "invented by",
                       "Brewster%2C+Sir+David");
    edgeTable.put("899-227", edge);
    edge = new DisplayedEdge(959, 1447,
                       "Langevin%2C+Paul",
                       "knew",
                       "Rutherford%2C+Ernest");
    edgeTable.put("959-1447", edge);
    edge = new BasicEdge(959, 428,
                       "Langevin%2C+Paul",
                       "lover of",
                       "Curie%2C+Marie");
    edgeTable.put("959-428", edge);
    edge = new BasicEdge(959, 524,
                       "Langevin%2C+Paul",
                       "might have anticipated",
                       "Einstein%2C+Albert");
    edgeTable.put("959-524", edge);
    edge = new BasicEdge(959, 235,
                       "Langevin%2C+Paul",
                       "knew",
                       "Broglie%2C+Louis%2C+Duke+de");
    edgeTable.put("959-235", edge);
    edge = new DisplayedEdge(959, 1546,
                       "Langevin%2C+Paul",
                       "he invented",
                       "Sonar");
    edgeTable.put("959-1546", edge);
    edge = new DisplayedEdge(959, 1806,
                       "Langevin%2C+Paul",
                       "taught",
                       "Zworykin%2C+Vladimir+Kosma");
    edgeTable.put("959-1806", edge);
    edge = new DisplayedEdge(963, 524,
                       "Laser",
                       "based on discovery by",
                       "Einstein%2C+Albert");
    edgeTable.put("963-524", edge);
    edge = new DisplayedEdge(970, 1497,
                       "Lawrence%2C+Thomas+Edward",
                       "a pal of",
                       "Shaw%2C+George+Bernard");
    edgeTable.put("970-1497", edge);
    edge = new DisplayedEdge(970, 254,
                       "Lawrence%2C+Thomas+Edward",
                       "a pal of",
                       "Buchan%2C+John");
    edgeTable.put("970-254", edge);
    edge = new DisplayedEdge(981, 1557,
                       "Leibniz%2C+Gottfried+Wilhelm",
                       "met",
                       "Spinoza%2C+Baruch");
    edgeTable.put("981-1557", edge);
    edge = new DisplayedEdge(981, 1713,
                       "Leibniz%2C+Gottfried+Wilhelm",
                       "satirized by",
                       "Voltaire%2C+Francois-Marie+Arouet+de");
    edgeTable.put("981-1713", edge);
    edge = new DisplayedEdge(981, 1464,
                       "Leibniz%2C+Gottfried+Wilhelm",
                       "work related to",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("981-1464", edge);
    edge = new DisplayedEdge(983, 1076,
                       "Lenin%2C+Vladimir+Ilich",
                       "influenced by",
                       "Marx%2C+Karl");
    edgeTable.put("983-1076", edge);
    edge = new DisplayedEdge(983, 1563,
                       "Lenin%2C+Vladimir+Ilich",
                       "assisted by",
                       "Stalin");
    edgeTable.put("983-1563", edge);
    edge = new DisplayedEdge(983, 1743,
                       "Lenin%2C+Vladimir+Ilich",
                       "interviewed by",
                       "Wells%2C+Herbert+George");
    edgeTable.put("983-1743", edge);
    edge = new DisplayedEdge(986, 1588,
                       "Lesseps%2C+Ferdinand%2C+Vicomte+de",
                       "built",
                       "Suez+Canal");
    edgeTable.put("986-1588", edge);
    edge = new DisplayedEdge(986, 1689,
                       "Lesseps%2C+Ferdinand%2C+Vicomte+de",
                       "work related to",
                       "Verdi%2C+Giuseppe+Fortunino+Francesco");
    edgeTable.put("986-1689", edge);
    edge = new DisplayedEdge(991, 518,
                       "Light+bulb",
                       "commonly thought to be invented by team led by",
                       "Edison%2C+Thomas+Alva");
    edgeTable.put("991-518", edge);
    edge = new DisplayedEdge(1001, 684,
                       "Liquid-fuel+rocket",
                       "was pioneered by",
                       "Goddard%2C+Robert+Hutchings");
    edgeTable.put("1001-684", edge);
    edge = new BasicEdge(1004, 450,
                       "Liszt%2C+Franz",
                       "visited by",
                       "Debussy%2C+Achille-Claude");
    edgeTable.put("1004-450", edge);
    edge = new DisplayedEdge(1004, 1048,
                       "Liszt%2C+Franz",
                       "approached by",
                       "Mahler%2C+Gustav");
    edgeTable.put("1004-1048", edge);
    edge = new DisplayedEdge(1038, 789,
                       "Mach%2C+Ernst",
                       "lectured on",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("1038-789", edge);
    edge = new DisplayedEdge(1038, 524,
                       "Mach%2C+Ernst",
                       "influenced",
                       "Einstein%2C+Albert");
    edgeTable.put("1038-524", edge);
    edge = new DisplayedEdge(1039, 1038,
                       "Mach+number",
                       "named after",
                       "Mach%2C+Ernst");
    edgeTable.put("1039-1038", edge);
    edge = new BasicEdge(1048, 1004,
                       "Mahler%2C+Gustav",
                       "sent first work to",
                       "Liszt%2C+Franz");
    edgeTable.put("1048-1004", edge);
    edge = new DisplayedEdge(1048, 1604,
                       "Mahler%2C+Gustav",
                       "premiere attended by",
                       "Tchaikovsky%2C+Peter+Ilich");
    edgeTable.put("1048-1604", edge);
    edge = new BasicEdge(1048, 619,
                       "Mahler%2C+Gustav",
                       "consulted",
                       "Freud%2C+Sigmund");
    edgeTable.put("1048-619", edge);
    edge = new DisplayedEdge(1061, 1076,
                       "Mao+Zedong",
                       "a follower of",
                       "Marx%2C+Karl");
    edgeTable.put("1061-1076", edge);
    edge = new DisplayedEdge(1061, 1563,
                       "Mao+Zedong",
                       "signed treaty with",
                       "Stalin");
    edgeTable.put("1061-1563", edge);
    edge = new BasicEdge(1062, 803,
                       "Marconi%2C+Guglielmo",
                       "inspired by",
                       "Hertz%2C+Heinrich+Rudolf");
    edgeTable.put("1062-803", edge);
    edge = new DisplayedEdge(1062, 1598,
                       "Marconi%2C+Guglielmo",
                       "a pal of",
                       "Swinton%2C+Alan+Archibald+Campbell");
    edgeTable.put("1062-1598", edge);
    edge = new DisplayedEdge(1062, 1664,
                       "Marconi%2C+Guglielmo",
                       "employed",
                       "Tykociner%2C+Joseph");
    edgeTable.put("1062-1664", edge);
    edge = new DisplayedEdge(1062, 1556,
                       "Marconi%2C+Guglielmo",
                       "met",
                       "Sperry%2C+Elmer+Ambrose");
    edgeTable.put("1062-1556", edge);
    edge = new BasicEdge(1076, 545,
                       "Marx%2C+Karl",
                       "collaborated with",
                       "Engels%2C+Friedrich");
    edgeTable.put("1076-545", edge);
    edge = new DisplayedEdge(1076, 1199,
                       "Marx%2C+Karl",
                       "influenced",
                       "Nehru%2C+Jawaharlal");
    edgeTable.put("1076-1199", edge);
    edge = new DisplayedEdge(1076, 1563,
                       "Marx%2C+Karl",
                       "influenced",
                       "Stalin");
    edgeTable.put("1076-1563", edge);
    edge = new DisplayedEdge(1117, 1168,
                       "Mesmer%2C+Franz+Anton",
                       "commissioned",
                       "Mozart%2C+Wolfgang+Amadeus");
    edgeTable.put("1117-1168", edge);
    edge = new BasicEdge(1117, 638,
                       "Mesmer%2C+Franz+Anton",
                       "influenced by",
                       "Galvani%2C+Luigi");
    edgeTable.put("1117-638", edge);
    edge = new DisplayedEdge(1117, 1464,
                       "Mesmer%2C+Franz+Anton",
                       "studied by",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("1117-1464", edge);
    edge = new BasicEdge(1168, 1117,
                       "Mozart%2C+Wolfgang+Amadeus",
                       "commissioned by",
                       "Mesmer%2C+Franz+Anton");
    edgeTable.put("1168-1117", edge);
    edge = new JourneyEdgeA(1168, 114,
                       "Mozart%2C+Wolfgang+Amadeus",
                       "used story by",
                       "Beaumarchais%2C+Caron+de");
    edgeTable.put("1168-1117", edge);
    edge = new BasicEdge(1168, 689,
                       "Mozart%2C+Wolfgang+Amadeus",
                       "set to music poems of",
                       "Goethe%2C+Johann+Wolfgang+von");
    edgeTable.put("1168-689", edge);
    edge = new DisplayedEdge(1186, 1713,
                       "Napoleon+Bonaparte",
                       "studied",
                       "Voltaire%2C+Francois-Marie+Arouet+de");
    edgeTable.put("1186-1713", edge);
    edge = new DisplayedEdge(1186, 449,
                       "Napoleon+Bonaparte",
                       "honoured",
                       "Davy%2C+Sir+Humphry");
    edgeTable.put("1186-449", edge);
    edge = new BasicEdge(1199, 1076,
                       "Nehru%2C+Jawaharlal",
                       "influenced by",
                       "Marx%2C+Karl");
    edgeTable.put("1199-1076", edge);
    edge = new DisplayedEdge(1201, 759,
                       "Nelson%2C+Horatio",
                       "cuckolded",
                       "Hamilton%2C+Sir+William");
    edgeTable.put("1201-759", edge);
    edge = new BasicEdge(1217, 789,
                       "Nipkow%2C+Paul+Gottlieb",
                       "taught by",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("1217-789", edge);
    edge = new DisplayedEdge(1217, 1806,
                       "Nipkow%2C+Paul+Gottlieb",
                       "invention superseded by",
                       "Zworykin%2C+Vladimir+Kosma");
    edgeTable.put("1217-1806", edge);
    edge = new DisplayedEdge(1227, 1464,
                       "Oersted%2C+Hans+Christian",
                       "studied work of",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("1227-1464", edge);
    edge = new DisplayedEdge(1241, 1730,
                       "Oscilloscope",
                       "was used by",
                       "Watson-Watt%2C+Robert");
    edgeTable.put("1241-1730", edge);
    edge = new DisplayedEdge(1241, 218,
                       "Oscilloscope",
                       "was invented by",
                       "Braun%2C+Karl+Ferdinand");
    edgeTable.put("1241-218", edge);
    edge = new DisplayedEdge(1317, 789,
                       "Planck%2C+Max",
                       "taught by",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("1317-789", edge);
    edge = new BasicEdge(1317, 524,
                       "Planck%2C+Max",
                       "a supporter of",
                       "Einstein%2C+Albert");
    edgeTable.put("1317-524", edge);
    edge = new BasicEdge(1317, 182,
                       "Planck%2C+Max",
                       "theory applied by",
                       "Bohr%2C+Niels+Henrik+David");
    edgeTable.put("1317-182", edge);
    edge = new BasicEdge(1317, 197,
                       "Planck%2C+Max",
                       "theory developed by",
                       "Born%2C+Max");
    edgeTable.put("1317-197", edge);
    edge = new BasicEdge(1317, 787,
                       "Planck%2C+Max",
                       "theory developed by",
                       "Heisenberg%2C+Werner+Karl");
    edgeTable.put("1317-787", edge);
    edge = new BasicEdge(1317, 235,
                       "Planck%2C+Max",
                       "work related to",
                       "Broglie%2C+Louis%2C+Duke+de");
    edgeTable.put("1317-235", edge);
    edge = new BasicEdge(1327, 815,
                       "Poe%2C+Edgar+Allan",
                       "wrote parody of",
                       "Hoffmann%2C+Ernst+Theodor+Amadeus");
    edgeTable.put("1327-815", edge);
    edge = new BasicEdge(1327, 450,
                       "Poe%2C+Edgar+Allan",
                       "influenced",
                       "Debussy%2C+Achille-Claude");
    edgeTable.put("1327-450", edge);
    edge = new JourneyEdgeI(1327, 1361,
                       "Poe%2C+Edgar+Allan",
                       "influenced",
                       "Rachmaninov%2C+Sergey");
    edgeTable.put("1327-450", edge);
    edge = new DisplayedEdge(1350, 619,
                       "psychoanalysis",
                       "initiated by",
                       "Freud%2C+Sigmund");
    edgeTable.put("1350-619", edge);
    edge = new DisplayedEdge(1356, 1357,
                       "Purkinje+cells",
                       "discovered by",
                       "Purkinje%2C+Jan+Evangelista");
    edgeTable.put("1356-1357", edge);
    edge = new DisplayedEdge(1357, 689,
                       "Purkinje%2C+Jan+Evangelista",
                       "admired by",
                       "Goethe%2C+Johann+Wolfgang+von");
    edgeTable.put("1357-689", edge);
    edge = new DisplayedEdge(1357, 637,
                       "Purkinje%2C+Jan+Evangelista",
                       "work related to",
                       "Galton%2C+Sir+Francis");
    edgeTable.put("1357-637", edge);
    edge = new DisplayedEdge(1357, 789,
                       "Purkinje%2C+Jan+Evangelista",
                       "influenced",
                       "Helmholtz%2C+Hermann+von");
    edgeTable.put("1357-789", edge);
    edge = new DisplayedEdge(1357, 445,
                       "Purkinje%2C+Jan+Evangelista",
                       "influenced by",
                       "Darwin%2C+Erasmus");
    edgeTable.put("1357-445", edge);
    edge = new DisplayedEdge(1358, 1447,
                       "Quantum+physics",
                       "pioneered by",
                       "Rutherford%2C+Ernest");
    edgeTable.put("1358-1447", edge);
    edge = new DisplayedEdge(1361, 1604,
                       "Rachmaninov%2C+Sergey",
                       "mentored by",
                       "Tchaikovsky%2C+Peter+Ilich");
    edgeTable.put("1361-1604", edge);
    edge = new BasicEdge(1361, 1327,
                       "Rachmaninov%2C+Sergey",
                       "inspired by",
                       "Poe%2C+Edgar+Allan");
    edgeTable.put("1361-1327", edge);
    edge = new JourneyEdgeJ(1361, 1517,
                       "Rachmaninov%2C+Sergey",
                       "invested in",
                       "Sikorsky%2C+Igor+Ivanovich");
    edgeTable.put("1361-1327", edge);
    edge = new DisplayedEdge(1361, 1048,
                       "Rachmaninov%2C+Sergey",
                       "was associated with",
                       "Mahler%2C+Gustav");
    edgeTable.put("1361-1048", edge);
    edge = new DisplayedEdge(1363, 1730,
                       "Radar",
                       "pioneered by",
                       "Watson-Watt%2C+Robert");
    edgeTable.put("1363-1730", edge);
    edge = new DisplayedEdge(1364, 1062,
                       "radio",
                       "pioneered by",
                       "Marconi%2C+Guglielmo");
    edgeTable.put("1364-1062", edge);
    edge = new DisplayedEdge(1365, 428,
                       "Radioactivity",
                       "pioneered by",
                       "Curie%2C+Marie");
    edgeTable.put("1365-428", edge);
    edge = new DisplayedEdge(1383, 460,
                       "Reductionism",
                       "inspired by",
                       "Descartes%2C+Rene");
    edgeTable.put("1383-460", edge);
    edge = new DisplayedEdge(1387, 524,
                       "Relativity",
                       "theory developed by",
                       "Einstein%2C+Albert");
    edgeTable.put("1387-524", edge);
    edge = new DisplayedEdge(1429, 1563,
                       "Roosevelt%2C+Pres.+Franklin+Delano",
                       "allied with",
                       "Stalin");
    edgeTable.put("1429-1563", edge);
    edge = new BasicEdge(1447, 182,
                       "Rutherford%2C+Ernest",
                       "worked with",
                       "Bohr%2C+Niels+Henrik+David");
    edgeTable.put("1447-182", edge);
    edge = new BasicEdge(1447, 959,
                       "Rutherford%2C+Ernest",
                       "work related to",
                       "Langevin%2C+Paul");
    edgeTable.put("1447-959", edge);
    edge = new DisplayedEdge(1447, 1546,
                       "Rutherford%2C+Ernest",
                       "work related to",
                       "Sonar");
    edgeTable.put("1447-1546", edge);
    edge = new DisplayedEdge(1447, 1317,
                       "Rutherford%2C+Ernest",
                       "corresponded with",
                       "Planck%2C+Max");
    edgeTable.put("1447-1317", edge);
    edge = new BasicEdge(1447, 524,
                       "Rutherford%2C+Ernest",
                       "corresponded with",
                       "Einstein%2C+Albert");
    edgeTable.put("1447-524", edge);
    edge = new BasicEdge(1447, 428,
                       "Rutherford%2C+Ernest",
                       "work related to",
                       "Curie%2C+Marie");
    edgeTable.put("1447-428", edge);
    edge = new DisplayedEdge(1447, 235,
                       "Rutherford%2C+Ernest",
                       "influenced",
                       "Broglie%2C+Louis%2C+Duke+de");
    edgeTable.put("1447-235", edge);
    edge = new DisplayedEdge(1447, 197,
                       "Rutherford%2C+Ernest",
                       "influenced",
                       "Born%2C+Max");
    edgeTable.put("1447-197", edge);
    edge = new DisplayedEdge(1447, 787,
                       "Rutherford%2C+Ernest",
                       "influenced",
                       "Heisenberg%2C+Werner+Karl");
    edgeTable.put("1447-787", edge);
    edge = new BasicEdge(1447, 209,
                       "Rutherford%2C+Ernest",
                       "taught",
                       "Bragg%2C+Sir+William+Henry");
    edgeTable.put("1447-209", edge);
    edge = new DisplayedEdge(1464, 1557,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "studied work of",
                       "Spinoza%2C+Baruch");
    edgeTable.put("1464-1557", edge);
    edge = new BasicEdge(1464, 689,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "work read by",
                       "Goethe%2C+Johann+Wolfgang+von");
    edgeTable.put("1464-689", edge);
    edge = new BasicEdge(1464, 981,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "read works of",
                       "Leibniz%2C+Gottfried+Wilhelm");
    edgeTable.put("1464-981", edge);
    edge = new BasicEdge(1464, 638,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "studied work of",
                       "Galvani%2C+Luigi");
    edgeTable.put("1464-638", edge);
    edge = new DisplayedEdge(1464, 1712,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "studied work of",
                       "Volta%2C+Alessandro");
    edgeTable.put("1464-1712", edge);
    edge = new BasicEdge(1464, 1117,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "studied work of",
                       "Mesmer%2C+Franz+Anton");
    edgeTable.put("1464-1117", edge);
    edge = new BasicEdge(1464, 545,
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von",
                       "taught",
                       "Engels%2C+Friedrich");
    edgeTable.put("1464-545", edge);
    edge = new DisplayedEdge(1497, 1743,
                       "Shaw%2C+George+Bernard",
                       "fellow-socialist was",
                       "Wells%2C+Herbert+George");
    edgeTable.put("1497-1743", edge);
    edge = new DisplayedEdge(1497, 1563,
                       "Shaw%2C+George+Bernard",
                       "admired",
                       "Stalin");
    edgeTable.put("1497-1563", edge);
    edge = new BasicEdge(1505, 95,
                       "Shockley%2C+William+Bradford",
                       "won Nobel with",
                       "Bardeen%2C+John");
    edgeTable.put("1505-95", edge);
    edge = new BasicEdge(1505, 217,
                       "Shockley%2C+William+Bradford",
                       "won Nobel with",
                       "Brattain%2C+Walter+Houser");
    edgeTable.put("1505-217", edge);
    edge = new JourneyEdgeK(1517, 788,
                       "Sikorsky%2C+Igor+Ivanovich",
                       "invented by",
                       "helicopter");
    edgeTable.put("1505-217", edge);
    edge = new BasicEdge(1517, 1361,
                       "Sikorsky%2C+Igor+Ivanovich",
                       "funded by",
                       "Rachmaninov%2C+Sergey");
    edgeTable.put("1517-1361", edge);
    edge = new BasicEdge(1545, 449,
                       "Somerville%2C+Mary",
                       "a pal of",
                       "Davy%2C+Sir+Humphry");
    edgeTable.put("1545-449", edge);
    edge = new DisplayedEdge(1545, 227,
                       "Somerville%2C+Mary",
                       "a pal of",
                       "Brewster%2C+Sir+David");
    edgeTable.put("1545-227", edge);
    edge = new BasicEdge(1546, 959,
                       "Sonar",
                       "invented by",
                       "Langevin%2C+Paul");
    edgeTable.put("1546-959", edge);
    edge = new BasicEdge(1546, 1447,
                       "Sonar",
                       "anticipated by",
                       "Rutherford%2C+Ernest");
    edgeTable.put("1546-1447", edge);
    edge = new DisplayedEdge(1548, 1664,
                       "Sound+on+film",
                       "was pioneered by",
                       "Tykociner%2C+Joseph");
    edgeTable.put("1548-1664", edge);
    edge = new DisplayedEdge(1551, 684,
                       "Spaceflight",
                       "developed by",
                       "Goddard%2C+Robert+Hutchings");
    edgeTable.put("1551-684", edge);
    edge = new BasicEdge(1553, 637,
                       "Spencer%2C+Herbert",
                       "a fan was",
                       "Galton%2C+Sir+Francis");
    edgeTable.put("1553-637", edge);
    edge = new BasicEdge(1553, 445,
                       "Spencer%2C+Herbert",
                       "admired",
                       "Darwin%2C+Erasmus");
    edgeTable.put("1553-445", edge);
    edge = new BasicEdge(1556, 518,
                       "Sperry%2C+Elmer+Ambrose",
                       "influenced by",
                       "Edison%2C+Thomas+Alva");
    edgeTable.put("1556-518", edge);
    edge = new DisplayedEdge(1556, 1614,
                       "Sperry%2C+Elmer+Ambrose",
                       "rival was",
                       "Tesla%2C+Nikola");
    edgeTable.put("1556-1614", edge);
    edge = new BasicEdge(1556, 1062,
                       "Sperry%2C+Elmer+Ambrose",
                       "met",
                       "Marconi%2C+Guglielmo");
    edgeTable.put("1556-1062", edge);
    edge = new DisplayedEdge(1557, 460,
                       "Spinoza%2C+Baruch",
                       "influenced by",
                       "Descartes%2C+Rene");
    edgeTable.put("1557-460", edge);
    edge = new BasicEdge(1557, 981,
                       "Spinoza%2C+Baruch",
                       "disputed by",
                       "Leibniz%2C+Gottfried+Wilhelm");
    edgeTable.put("1557-981", edge);
    edge = new BasicEdge(1557, 1464,
                       "Spinoza%2C+Baruch",
                       "influenced",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("1557-1464", edge);
    edge = new JourneyEdgeF(1560, 594,
                       "Spurzheim%2C+Johann",
                       "his elogy given by",
                       "Follen%2C+Karl");
    edgeTable.put("1557-1464", edge);
    edge = new BasicEdge(1563, 1076,
                       "Stalin",
                       "influenced by",
                       "Marx%2C+Karl");
    edgeTable.put("1563-1076", edge);
    edge = new BasicEdge(1563, 983,
                       "Stalin",
                       "worked with",
                       "Lenin%2C+Vladimir+Ilich");
    edgeTable.put("1563-983", edge);
    edge = new DisplayedEdge(1563, 1743,
                       "Stalin",
                       "a fan was",
                       "Wells%2C+Herbert+George");
    edgeTable.put("1563-1743", edge);
    edge = new BasicEdge(1563, 1497,
                       "Stalin",
                       "a fan was",
                       "Shaw%2C+George+Bernard");
    edgeTable.put("1563-1497", edge);
    edge = new BasicEdge(1563, 1061,
                       "Stalin",
                       "a pal of",
                       "Mao+Zedong");
    edgeTable.put("1563-1061", edge);
    edge = new BasicEdge(1588, 986,
                       "Suez+Canal",
                       "build by",
                       "Lesseps%2C+Ferdinand%2C+Vicomte+de");
    edgeTable.put("1588-986", edge);
    edge = new BasicEdge(1598, 1062,
                       "Swinton%2C+Alan+Archibald+Campbell",
                       "a pal of",
                       "Marconi%2C+Guglielmo");
    edgeTable.put("1598-1062", edge);
    edge = new DisplayedEdge(1598, 1806,
                       "Swinton%2C+Alan+Archibald+Campbell",
                       "influenced",
                       "Zworykin%2C+Vladimir+Kosma");
    edgeTable.put("1598-1806", edge);
    edge = new BasicEdge(1604, 450,
                       "Tchaikovsky%2C+Peter+Ilich",
                       "shared patron with",
                       "Debussy%2C+Achille-Claude");
    edgeTable.put("1604-450", edge);
    edge = new BasicEdge(1604, 1048,
                       "Tchaikovsky%2C+Peter+Ilich",
                       "attended premiere of",
                       "Mahler%2C+Gustav");
    edgeTable.put("1604-1048", edge);
    edge = new BasicEdge(1604, 1361,
                       "Tchaikovsky%2C+Peter+Ilich",
                       "mentored",
                       "Rachmaninov%2C+Sergey");
    edgeTable.put("1604-1361", edge);
    edge = new BasicEdge(1607, 126,
                       "Telephone",
                       "invented by",
                       "Bell%2C+Alexander+Graham");
    edgeTable.put("1607-126", edge);
    edge = new BasicEdge(1614, 518,
                       "Tesla%2C+Nikola",
                       "worked for",
                       "Edison%2C+Thomas+Alva");
    edgeTable.put("1614-518", edge);
    edge = new DisplayedEdge(1614, 1748,
                       "Tesla%2C+Nikola",
                       "worked for",
                       "Westinghouse");
    edgeTable.put("1614-1748", edge);
    edge = new BasicEdge(1614, 1556,
                       "Tesla%2C+Nikola",
                       "rival was",
                       "Sperry%2C+Elmer+Ambrose");
    edgeTable.put("1614-1556", edge);
    edge = new DisplayedEdge(1614, 1664,
                       "Tesla%2C+Nikola",
                       "met",
                       "Tykociner%2C+Joseph");
    edgeTable.put("1614-1664", edge);
    edge = new DisplayedEdge(1648, 95,
                       "Transistor",
                       "co-invented by",
                       "Bardeen%2C+John");
    edgeTable.put("1648-95", edge);
    edge = new DisplayedEdge(1648, 217,
                       "Transistor",
                       "co-invented by",
                       "Brattain%2C+Walter+Houser");
    edgeTable.put("1648-217", edge);
    edge = new DisplayedEdge(1648, 1505,
                       "Transistor",
                       "co-invented by",
                       "Shockley%2C+William+Bradford");
    edgeTable.put("1648-1505", edge);
    edge = new DisplayedEdge(1662, 1217,
                       "TV",
                       "development aided by",
                       "Nipkow%2C+Paul+Gottlieb");
    edgeTable.put("1662-1217", edge);
    edge = new DisplayedEdge(1662, 1806,
                       "TV",
                       "early development by",
                       "Zworykin%2C+Vladimir+Kosma");
    edgeTable.put("1662-1806", edge);
    edge = new DisplayedEdge(1662, 218,
                       "TV",
                       "related to work of",
                       "Braun%2C+Karl+Ferdinand");
    edgeTable.put("1662-218", edge);
    edge = new DisplayedEdge(1662, 1598,
                       "TV",
                       "early development by",
                       "Swinton%2C+Alan+Archibald+Campbell");
    edgeTable.put("1662-1598", edge);
    edge = new BasicEdge(1664, 1614,
                       "Tykociner%2C+Joseph",
                       "met",
                       "Tesla%2C+Nikola");
    edgeTable.put("1664-1614", edge);
    edge = new BasicEdge(1664, 1062,
                       "Tykociner%2C+Joseph",
                       "worked for",
                       "Marconi%2C+Guglielmo");
    edgeTable.put("1664-1062", edge);
    edge = new DisplayedEdge(1664, 1806,
                       "Tykociner%2C+Joseph",
                       "a pal of",
                       "Zworykin%2C+Vladimir+Kosma");
    edgeTable.put("1664-1806", edge);
    edge = new BasicEdge(1664, 428,
                       "Tykociner%2C+Joseph",
                       "work related to",
                       "Curie%2C+Marie");
    edgeTable.put("1664-428", edge);
    edge = new DisplayedEdge(1689, 1588,
                       "Verdi%2C+Giuseppe+Fortunino+Francesco",
                       "wrote Aida for opening of",
                       "Suez+Canal");
    edgeTable.put("1689-1588", edge);
    edge = new BasicEdge(1689, 986,
                       "Verdi%2C+Giuseppe+Fortunino+Francesco",
                       "work related to",
                       "Lesseps%2C+Ferdinand%2C+Vicomte+de");
    edgeTable.put("1689-986", edge);
    edge = new DisplayedEdge(1689, 464,
                       "Verdi%2C+Giuseppe+Fortunino+Francesco",
                       "met",
                       "Diaghilev%2C+Sergei+Pavlovich");
    edgeTable.put("1689-464", edge);
    edge = new DisplayedEdge(1712, 449,
                       "Volta%2C+Alessandro",
                       "influenced",
                       "Davy%2C+Sir+Humphry");
    edgeTable.put("1712-449", edge);
    edge = new BasicEdge(1712, 638,
                       "Volta%2C+Alessandro",
                       "disagreed with",
                       "Galvani%2C+Luigi");
    edgeTable.put("1712-638", edge);
    edge = new BasicEdge(1712, 1464,
                       "Volta%2C+Alessandro",
                       "work related to",
                       "Schelling%2C+Frederick+Wilhelm+Joseph+von");
    edgeTable.put("1712-1464", edge);
    edge = new BasicEdge(1713, 116,
                       "Voltaire%2C+Francois-Marie+Arouet+de",
                       "wrote preface for",
                       "Beccaria%2C+Cesare");
    edgeTable.put("1713-116", edge);
    edge = new BasicEdge(1713, 114,
                       "Voltaire%2C+Francois-Marie+Arouet+de",
                       "a fan was",
                       "Beaumarchais%2C+Caron+de");
    edgeTable.put("1713-114", edge);
    edge = new BasicEdge(1713, 981,
                       "Voltaire%2C+Francois-Marie+Arouet+de",
                       "satirized",
                       "Leibniz%2C+Gottfried+Wilhelm");
    edgeTable.put("1713-981", edge);
    edge = new BasicEdge(1730, 1241,
                       "Watson-Watt%2C+Robert",
                       "used",
                       "Oscilloscope");
    edgeTable.put("1730-1241", edge);
    edge = new DisplayedEdge(1731, 445,
                       "Watt%2C+James",
                       "met",
                       "Darwin%2C+Erasmus");
    edgeTable.put("1731-445", edge);
    edge = new BasicEdge(1731, 876,
                       "Watt%2C+James",
                       "work related to",
                       "Jefferson%2C+Pres.+Thomas");
    edgeTable.put("1731-876", edge);
    edge = new DisplayedEdge(1738, 445,
                       "Wedgwood%2C+Josiah",
                       "a pal of",
                       "Darwin%2C+Erasmus");
    edgeTable.put("1738-445", edge);
    edge = new DisplayedEdge(1738, 759,
                       "Wedgwood%2C+Josiah",
                       "influenced by",
                       "Hamilton%2C+Sir+William");
    edgeTable.put("1738-759", edge);
    edge = new BasicEdge(1743, 1497,
                       "Wells%2C+Herbert+George",
                       "met",
                       "Shaw%2C+George+Bernard");
    edgeTable.put("1743-1497", edge);
    edge = new BasicEdge(1743, 871,
                       "Wells%2C+Herbert+George",
                       "knew",
                       "James%2C+Henry");
    edgeTable.put("1743-871", edge);
    edge = new DisplayedEdge(1743, 684,
                       "Wells%2C+Herbert+George",
                       "influenced",
                       "Goddard%2C+Robert+Hutchings");
    edgeTable.put("1743-684", edge);
    edge = new BasicEdge(1743, 983,
                       "Wells%2C+Herbert+George",
                       "interviewed",
                       "Lenin%2C+Vladimir+Ilich");
    edgeTable.put("1743-983", edge);
    edge = new BasicEdge(1743, 1563,
                       "Wells%2C+Herbert+George",
                       "interviewed",
                       "Stalin");
    edgeTable.put("1743-1563", edge);
    edge = new BasicEdge(1748, 1614,
                       "Westinghouse",
                       "employed",
                       "Tesla%2C+Nikola");
    edgeTable.put("1748-1614", edge);
    edge = new BasicEdge(1748, 518,
                       "Westinghouse",
                       "rival was",
                       "Edison%2C+Thomas+Alva");
    edgeTable.put("1748-518", edge);
    edge = new DisplayedEdge(1800, 804,
                       "Zionism",
                       "founded by",
                       "Herzl%2C+Theodor");
    edgeTable.put("1800-804", edge);
    edge = new BasicEdge(1806, 959,
                       "Zworykin%2C+Vladimir+Kosma",
                       "taught by",
                       "Langevin%2C+Paul");
    edgeTable.put("1806-959", edge);
    edge = new BasicEdge(1806, 1664,
                       "Zworykin%2C+Vladimir+Kosma",
                       "served under",
                       "Tykociner%2C+Joseph");
    edgeTable.put("1806-1664", edge);
    edge = new BasicEdge(1806, 1217,
                       "Zworykin%2C+Vladimir+Kosma",
                       "work related to",
                       "Nipkow%2C+Paul+Gottlieb");
    edgeTable.put("1806-1217", edge);
    edge = new BasicEdge(1806, 1598,
                       "Zworykin%2C+Vladimir+Kosma",
                       "work related to",
                       "Swinton%2C+Alan+Archibald+Campbell");
    edgeTable.put("1806-1598", edge);
    edge = new BasicEdge(1806, 1662,
                       "Zworykin%2C+Vladimir+Kosma",
                       "a developer of",
                       "TV");
    edgeTable.put("1806-1662", edge);
  }

  /**
   * Get an instance of this class.
   * Implements the singleton design pattern.
   * @return reference to only instance of this class
   */
  static public EdgeData getInstance()
  {
    if (edgeData == null) edgeData = new EdgeData();
    return edgeData;
  }

  /**
   * Get a directed edge object connecting a pair of nodes.
   * 
   * Because edges are directed there can be, and often are, two edges
   * connecting a pair of nodes.  Only the edge specified in the
   * source to destination direction is returned, (if any). The edge
   * for the reverse direction (if any) can be obtained by transposing
   * the two parameters. (Only strings containing numerics have any
   * hope of success.)
   * 
   * While the Edge object returned is a BasicEdge, the actual object is
   * likely to be a derived class object.  See the Edge class references in
   * this class declaration (above). 
   * 
   * @param srcNodeId Node ID of the edge source node.
   * @param dstNodeId Node ID of the edge destination node
   * @return an Edge Object or <code>null</code> if none
   */
  public BasicEdge getEdge(String srcNodeId, String dstNodeId)
  {
    try
      {
        Integer.parseInt(srcNodeId);
        Integer.parseInt(dstNodeId);
      }
    catch (NumberFormatException e)
      {
        return null;
      }
    String key = srcNodeId + "-" + dstNodeId;
    return edgeTable.get(key);
  }

  /**
   * Get a directed edge object connecting a pair of nodes.
   * 
   * Because edges are directed there can be, and often are, two edges
   * connecting a pair of nodes.  Only the edge specified in the
   * source to destination direction is returned, (if any). The edge
   * for the reverse direction (if any) can be obtained by transposing
   * the two parameters.
   * 
   * While the Edge object returned is a BasicEdge, the actual object is
   * likely to be a derived class object.  See the Edge class references in
   * this class declaration (above). 
   * 
   * @param srcNodeId Node ID of the edge source node.
   * @param dstNodeId Node ID of the edge destination node
   * @return an Edge Object or <code>null</code> if none
   */
  public BasicEdge getEdge(int srcNodeId, int dstNodeId)
  {
    String key = Integer.toString(srcNodeId) + "-" + Integer.toString(dstNodeId);
    return edgeTable.get(key);
  }

  /**
   * Get an enumeration of all the Edge objects.
   * 
   * Use the Enumeration methods on the returned object to fetch each Edge
   * object sequentially.
   * 
   * @return an Enumeration object for retreiving Edge objects
   */
  public Enumeration<BasicEdge> elements()
  {
    return edgeTable.elements();
  }
}
