/*
 * FileChooser.java
 *
 * Created on 2007/01/11, 11:02
 */

package org.jdesktop.lg3d.apps.jsaddle;

import java.io.File;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  Yasuhiro Fujitsuki(thaniwa)
 */
public class FileChooser extends javax.swing.JPanel {
    
    private JSaddleManager manager = null;
    
    /** Creates new form FileChooser */
    public FileChooser() {
        initComponents();
        addComponents();
    }
    
    public FileChooser(JSaddleManager manager){
        this.manager = manager;
        initComponents();
        addComponents();
    }

    public void addComponents(){
        this.jFileChooser1.addChoosableFileFilter(pdfFilter);
    }

    // image filter
    private FileFilter pdfFilter = new FileFilter() {
        public boolean accept(File f) {
            boolean result = false;
            if( f != null ) {
                if ( f.isDirectory() )
                    result = true;
                else {
                    String name = f.getName();
                    if( name != null && 
                            ( name.toLowerCase().endsWith(".pdf") )
                    )
                        result = true;
                }
            }            
            return result;
        }
        public String getDescription(){
            return "PDF";
        }
    };
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setMinimumSize(new java.awt.Dimension(527, 336));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jFileChooser1, gridBagConstraints);

        jButton1.setText("Load a Manual PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jButton1, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // File file = new File(url.getPath());
        try{
            this.manager.deocdeResourceURL("org/jdesktop/lg3d/apps/jsaddle/resources/jsaddle_usage_en.pdf");
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // System.out.println("Modifies :" + evt.getActionCommand() );
        if( evt.getActionCommand().trim().equals("ApproveSelection") ){
            try{
                File file = this.jFileChooser1.getSelectedFile();
                if( file != null && file.isDirectory() == false ){
                    String path = file.getCanonicalPath();
                    this.manager.decodePdf(file.getCanonicalPath());
                }
            } catch (java.io.IOException e){
                e.printStackTrace();
            }
        }
        // else if( evt.getActionCommand().trim().equals("CancelSelection") ){
        // }
    }//GEN-LAST:event_jFileChooser1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
    
}
