/*
 * mp3pluginWarningFrame.java
 *
 * Created on 2006/08/07, 13:42
 */

package org.jdesktop.lg3d.apps.trumplayer.utils;

import org.jdesktop.lg3d.apps.trumplayer.Main;
import java.util.ResourceBundle;
import javax.swing.JFrame;

/**
 *
 * @author  Yasuhiro Fujitsuki (thaniwa)
 */
public class mp3pluginWarningFrame extends javax.swing.JFrame {
    
    /** Creates new form mp3pluginWarningFrame */
    public mp3pluginWarningFrame() {
        initComponents();
        setLabels();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        okayButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Dialog", 1, 14));
        messageArea.setColumns(32);
        messageArea.setEditable(false);
        messageArea.setFont(new java.awt.Font("Dialog", 1, 14));
        messageArea.setRows(5);
        messageArea.setText("\nJava MP3 Plugin was not found in CLASSPATH.\nTrumplayer requires mp3plugin.jar to play mp3 music file.\nIf you want to play mp3 music, please install it.\n");
        messageArea.setCaretColor(new java.awt.Color(0, 0, 0));
        messageArea.setMinimumSize(new java.awt.Dimension(40, 22));
        jScrollPane1.setViewportView(messageArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        okayButton.setText("Okay");
        okayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(okayButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
        windowCloseAction();
    }//GEN-LAST:event_formWindowClosed

    private void okayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayButtonActionPerformed
// TODO add your handling code here:
        windowCloseAction();
    }//GEN-LAST:event_okayButtonActionPerformed

    private void setLabels(){
        ResourceBundle resource = ResourceBundle.getBundle("org.jdesktop.lg3d.apps.trumplayer.resources.messages");
        if(resource != null){
            okayButton.setText(resource.getString("mp3pluginWarningFrame.okay"));
            messageArea.setText(resource.getString("mp3pluginWarningFrame.warning"));
        }
    }
    
    private void windowCloseAction(){
        if( isVisible ){
            isVisible = false;
            frame.setVisible(false);
            frame.dispose();
            Main.startup();
        }
    }
    
    private static boolean isVisible = true;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mp3pluginWarningFrame().setVisible(true);
            }
        });
    }
    
    private JFrame frame = this;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JButton okayButton;
    // End of variables declaration//GEN-END:variables
    
}
