lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
Re: Google bounties ?
Hi Alvaro,
 
> I submitted my application to Google to participate
> in SoC, in the web search project. I made my wiki
> page, and submitted the JCA, and so on.
 
 
Yes, we've surely received your JCA. Thank you!
 
> I updated my wiki a bit today, If you want to have a
> look at it, it's right here:
> http://wiki.java.net/bin/view/People/AlvaroSalmador
 
Thanks for sharing this with the community too!
 
hideya
--------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net
