lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
JavaOne: LG3D Activities Updated
Hi LG3D Community Folks,
 
I've updated the JavaOne LG3D Activity list at:
https://lg3d.dev.java.net/#JavaOne-2005-Activities
 
(1) Sometime between 12:00-1:00pm or 4:00-5:00pm, 6/26 (Sun)
LG3D demo during NetBeans Day Keynote
hosted by James Gosling.
 
(2) 6/27-29
LG3D on Sharp's 3D LCD laptop!
 
(3) 6/27-29
Demonstration of an experimental port of
LG3D to an embedded system evaluation board
 
hideya
--------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net
