lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
Re: Updated Blackgoat 
wow dai, what an impressive evolution from the last one. 
Keep the good work going up.
  
--
opsi
--
Indifference will be the downfall of mankind, but who cares?
 
--------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net

