lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
Google's "Summer of Code" lists LG3D as a participating org
LG3D コミュニティのみなさま，
 
学生の方々に朗報です．LG3DがGoogleの"Summer of Code"に参加団体として
登録されましたっ！
 
http://code.google.com/summerofcode.html
This Summer, don't let your programming skills lie fallow...
Google will provide a $4500 award to each student who successfully 
completes an open source project by the end of the Summer.
 
プロジェクトのリスト（ドラフト）はこちらです：
http://wiki.java.net/bin/view/Javadesktop/SummerOfCode2005
 
取り急ぎ...
 
ひでや
--------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net

