lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
Re: 3D web browser
The following pure java xhtml renderer may prove useful for 3D browser experiments https://xhtmlrenderer.dev.java.net/. The renderer will render to a buffered image so it should integrate nicely with lg3d.

The renderer only handles compliant xhtml so it's not ready for use a general web browser. This project can help fix the format of noncompliant content https://xhtmltranscoder.dev.java.net/

If anyone has the time and inclination to dig a little deeper and perhaps produce a basic browser that would be really cool.....