lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
Re: First Shader example available
On Mon, 2005-06-13 at 12:49 -0400, lg3d-interest@javadesktop.org wrote:
> When shaders are running the CD's are gold with a dimpled surface, 
it's not at all subtle.
 
Which means that your picture Juan should be named shaders-here.png
I've put it up on my site for all of those that don't get the
attachments:
 
http://gameldar.fdns.net/lg3d/shaders-here.png
 
Kirk
--------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net
