/*
 * SearchSwingPanel.java
 *
 * Created on 2007/06/02, 15:17
 */

package org.jdesktop.lg3d.apps.trumplayer;

import org.jdesktop.lg3d.apps.trumplayer.base.AlbumSearch;
import org.jdesktop.lg3d.wg.Component3D;

/**
 *
 * @author  Yasuhiro Fujitsuki (thaniwa)
 */
public class SearchSwingPanel extends javax.swing.JPanel {

    private Component3D parent = null;
    private UpdateBySearch target = null;
    
    /** Creates new form SearchSwingPanel */
    public SearchSwingPanel(Component3D component, UpdateBySearch target) {
        parent = component;
        this.target = target;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        artistLabel = new javax.swing.JLabel();
        albumLabel = new javax.swing.JLabel();
        artistTextField = new javax.swing.JTextField();
        albumTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        artistLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        artistLabel.setText("artist");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 22, 3, 12);
        add(artistLabel, gridBagConstraints);

        albumLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        albumLabel.setText("album");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 12);
        add(albumLabel, gridBagConstraints);

        artistTextField.setFont(new java.awt.Font("Dialog", 0, 18));
        artistTextField.setMinimumSize(new java.awt.Dimension(240, 24));
        artistTextField.setPreferredSize(new java.awt.Dimension(240, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 15);
        add(artistTextField, gridBagConstraints);

        albumTextField.setFont(new java.awt.Font("Dialog", 0, 18));
        albumTextField.setMinimumSize(new java.awt.Dimension(240, 25));
        albumTextField.setPreferredSize(new java.awt.Dimension(240, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 15);
        add(albumTextField, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        searchButton.setFont(new java.awt.Font("Dialog", 1, 18));
        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jPanel1.add(searchButton);

        cancelButton.setFont(new java.awt.Font("Dialog", 1, 18));
        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 9, 15);
        add(jPanel1, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// TODO add your handling code here:
        parent.changeVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
// TODO add your handling code here:
        AlbumSearch search = AlbumSearch.getAlbumSearch();
        if( target != null )
            target.updateAlbumInformations(
                    search.search(artistTextField.getText(),albumTextField.getText())
                    );
        parent.changeVisible(false);
    }//GEN-LAST:event_searchButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albumLabel;
    private javax.swing.JTextField albumTextField;
    private javax.swing.JLabel artistLabel;
    private javax.swing.JTextField artistTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
    
}
