lg3d-interest@javadesktop.org
08/11/05 2:59 AM 
Re: Possible optimisation in TextureLoader
Nice change! That's a pretty significant savings for apps that are
texture heavy. It makes a noticable difference for BgManager and
K1WebDemo on my machine.

- Colin

---------------------------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net