lg3d-interest@javadesktop.org
08/22/05 18:13PM PDT
lg3d-session crash on Solaris 10
I tried lg3d 0.70 on Solaris 10.
 
lg3d-app and dev worked fine.
 
But when I tried to launch lg3d-session, following the 
instructions provided, It tries to start, but it crashes 
back to the gray console with a "|Class" error. 
Any suggestions?
 
Harware:
Athlon XP 2000+
768 MB RAM
NVIDIA FX5200
 
 
--------------------------------------------------
To unsubscribe, e-mail: interest-unsubscribe@lg3d.dev.java.net
For additional commands, e-mail: interest-help@lg3d.dev.java.net
